/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wjubqrmiomuxkcnaztdh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqdWJxcm1pb211eGtjbmF6dGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NzY5MzEsImV4cCI6MjA3OTU1MjkzMX0.ryPuRBPgB-Nz_EJdX-KypQ5L-IibQYB_gZQHF2nPfMQ"